<?php


namespace Rhubarb\Scaffolds\Migrations\Tests\Fixtures;


use Rhubarb\Scaffolds\Migrations\MigrationsManager;
use Rhubarb\Scaffolds\Migrations\Scripts\MigrationScriptInterface;

class TestMigrationsManager extends MigrationsManager
{
    /**@deprecated should only be used for testing
     * @param MigrationScriptInterface[] $migrationScripts
     */
    public function setMigrationScripts(array $migrationScripts)
    {
        $this->migrationScripts = $migrationScripts;
        $this->scriptsInstantiated = true;
    }

    /**@deprecated should only ever be used for testing
     * @param string[] $migrationScriptsClasses
     */
    public function setMigrationScriptsClasses(array $migrationScriptsClasses) {
        $this->migrationScriptClasses = $migrationScriptsClasses;
        $this->scriptsInstantiated = false;
    }

    /**@deprecated test function
     * @return string[]
     */
    public function getMigrationScriptClasses()
    {
        return parent::getMigrationScriptClasses(); // TODO: Change the autogenerated stub
    }

}